# Use entrypoint script instead prevents autocomplete from working
source /opt/ros/jazzy/setup.bash
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

export PATH=~/.local/bin:"$PATH"
