# Use entrypoint script instead prevents autocomplete from working
source /opt/ros/jazzy/setup.bash
source install/setup.sh
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

if [ -f .venv/bin/activate ]; then
    source .venv/bin/activate
fi

export PATH=~/.local/bin:"$PATH"
