FROM osrf/ros:jazzy-desktop-full

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=1000

# Add user to groups and configure sudo
RUN usermod -aG dialout,video ${USERNAME} \
    && mkdir -p /home/${USERNAME}/.config \
    && chown ${USER_UID}:${USER_GID} /home/${USERNAME}/.config \
    && apt-get update \
    && apt-get install -y --no-install-recommends sudo curl wget \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME} \
    && rm -rf /var/lib/apt/lists/*


# Install stonefish
RUN apt-get update \
    && apt-get install -y --no-install-recommends libglm-dev libsdl2-dev libfreetype6-dev git cmake build-essential \
    && git clone --depth 1 --single-branch -b fixes-merged https://github.com/kethan1/stonefish /tmp/stonefish \
    && cd /tmp/stonefish \
    && mkdir build && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Release \
    && make -j$(nproc) \
    && make install \
    && rm -rf /tmp/stonefish \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-pip python3-numpy python3-opencv ros-jazzy-rtabmap-ros \
    && python3 -m pip install --break-system-packages --no-cache-dir kornia torch onnxruntime ultralytics \
    && rm -rf /var/lib/apt/lists/*

# Install updated mesa drivers
# Greatly improves Gazebo performance for systems with newer AMD gpus
# Shouldn't affect other systems and shouldn't change install size too much
# TODO: Run these commands only when host system has AMD gpu / when needed, might need to move out of Dockerfile?
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository ppa:kisak/turtle -y \
    && apt-get install -y --no-install-recommends libgl1-mesa-dri libglx-mesa0 libegl1 libgbm1 mesa-vulkan-drivers mesa-utils \
    && rm -rf /var/lib/apt/lists/*

COPY --chown=${USERNAME}:${USERNAME} bashrc /home/${USERNAME}/.bashrc

ENV SHELL=/bin/bash

USER $USERNAME
CMD ["/bin/bash"]
