FROM osrf/ros:jazzy-desktop-full
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && usermod -aG dialout $USERNAME \
    && usermod -aG video $USERNAME \
    && mkdir /home/$USERNAME/.config && chown $USER_UID:$USER_GID /home/$USERNAME/.config \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*

# Install stonefish
RUN apt-get update \
    && apt-get install -y libglm-dev libsdl2-dev libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/kethan1/stonefish \
    && cd stonefish \
    && git switch fixes-merged \
    && mkdir build && cd build \
    && cmake .. \
    && make -j4 \
    && sudo make install

# Install updated mesa drivers
# Greatly improves Gazebo performance for systems with newer AMD gpus
# Shouldn't affect other systems and shouldn't change install size too much
# TODO: Run these commands only when host system has AMD gpu / when needed, might need to move out of Dockerfile?
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:kisak/turtle \
    && apt-get install -y libgl1-mesa-dri libglx-mesa0 libegl1 libgbm1 mesa-vulkan-drivers mesa-utils \
    && rm -rf /var/lib/apt/lists/*

COPY bashrc /home/${USERNAME}/.bashrc

ENV SHELL /bin/bash

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
CMD ["/bin/bash"]