<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sub_bringup</name>
  <version>0.0.0</version>
  <description>Launch and configuration files</description>
  <maintainer email="avbotzco@gmail.com">AVBotz</maintainer>
  <license>Proprietary</license>

  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rtabmap_odom</exec_depend>
  <exec_depend>rtabmap_sync</exec_depend>
  <exec_depend>sim_labeling</exec_depend>
  <exec_depend>spinnaker_camera_driver</exec_depend>
  <exec_depend>stonefish_ros2</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sub_color_correction</exec_depend>
  <exec_depend>sub_control</exec_depend>
  <exec_depend>sub_control_interfaces</exec_depend>
  <exec_depend>sub_serial_drivers</exec_depend>
  <exec_depend>sub_sim_sensors</exec_depend>
  <exec_depend>sub_sim</exec_depend>
  <exec_depend>sub_vision</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <exec_depend>waterlinked_dvl_driver</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
