/**:
  ros__parameters:
    control_rate_hz: 50.0
    power_limit: 0.6

    pos_pid:
      x: [0.8, 0.1, 0.0, 1.0]
      y: [0.8, 0.1, 0.0, 1.0]
      z: [0.7, 0.1, 0.0, 0.7]

    vel_pid:
      x: [30.0, 3.0, 0.0, 50.0]
      y: [30.0, 3.0, 0.0, 50.0]
      z: [38.0, 5.0, 0.0, 60.0]

    att_pid:
      x: [3.0, 0.5, 0.0, 4.0]
      y: [3.0, 0.5, 0.0, 4.0]
      z: [1.5, 0.1, 0.0, 4.0]

    ang_pid:
      x: [3.5, 0.1, 0.0, 20.0]
      y: [3.5, 0.1, 0.0, 20.0]
      z: [4.5, 0.1, 0.0, 20.0]
