# Cascade PID gains for sub_control. Written by tune_pid.py.
# parameter name: gains.<loop>.<axis>.<k>
/**:
  ros__parameters:
    gains:
      ang:
        x:
          kp: 4.00841
          ki: 0.89232
          kd: 1.014
        y:
          kp: 10.17042
          ki: 0.50189
          kd: 0.78234
        z:
          kp: 10.088
          ki: 0.9152
          kd: 1.5
      att:
        x:
          kp: 1.5
          ki: 0.12
          kd: 0.15
        y:
          kp: 0.31155
          ki: 0.15972
          kd: 0.0
        z:
          kp: 1.003
          ki: 0.08712
          kd: 0.0
      pos:
        x:
          kp: 0.8
          ki: 0.064
          kd: 0.08
        y:
          kp: 0.8
          ki: 0.064
          kd: 0.08
        z:
          kp: 0.8
          ki: 0.064
          kd: 0.08
      vel:
        x:
          kp: 32.59615
          ki: 4.39848
          kd: 4.99827
        y:
          kp: 87.88
          ki: 5.408
          kd: 7.28802
        z:
          kp: 61.5498
          ki: 8.83397
          kd: 12.2694
