/marlin_v2/ekf_filter_node:
    ros__parameters:
        debug: false

        frequency: 20.0

        map_frame: map
        odom_frame: marlin_v2/odom
        base_link_frame: marlin_v2/base_link
        world_frame: marlin_v2/odom

        imu0: imu_enu
        imu0_config: [
                      false, false, false,
                      true, true, true,
                      false, false, false,
                      true, true, true,
                      false, false, false]

        odom0: dvl_odom
        odom0_config: [false, false, false,
                      false, false, false,
                      true, true, true,
                      false, false, false,
                      false, false, false]