/**:
  ros__parameters:
    video_device: "/dev/front_camera"
    image_width: 1280
    image_height: 720
    framerate: 30.0
    pixel_format: "mjpeg"
    output_encoding: "rgb8"
    io_method: "mmap"
    frame_id: "marlin_v2/front_camera"
    camera_name: "logitech_c922_webcam"

    # Camera Control Parameters
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    autoexposure: true
    autofocus: false
