thruster_ids:
  thruster_0:
    control_tf: marlin_v2/thruster_0_link
    command_topic: control/thruster_0
    force_topic: control/force/thruster_0
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_1:
    control_tf: marlin_v2/thruster_1_link
    command_topic: control/thruster_1
    force_topic: control/force/thruster_1
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_2:
    control_tf: marlin_v2/thruster_2_link
    command_topic: control/thruster_2
    force_topic: control/force/thruster_2
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_3:
    control_tf: marlin_v2/thruster_3_link
    command_topic: control/thruster_3
    force_topic: control/force/thruster_3
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_4:
    control_tf: marlin_v2/thruster_4_link
    command_topic: control/thruster_4
    force_topic: control/force/thruster_4
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_5:
    control_tf: marlin_v2/thruster_5_link
    command_topic: control/thruster_5
    force_topic: control/force/thruster_5
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_6:
    control_tf: marlin_v2/thruster_6_link
    command_topic: control/thruster_6
    force_topic: control/force/thruster_6
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

  thruster_7:
    control_tf: marlin_v2/thruster_7_link
    command_topic: control/thruster_7
    force_topic: control/force/thruster_7
    limits: [-1.94, 2.43]
    delta_limit: 2.0
    polynomials:
      [
        3.61578007e-01,
        -2.79239790e+00,
        -6.65435249e-01,
        5.50620601e+00,
        9.16153193e-01,
        1.95251314e+00,
        9.21397833e-04,
      ]
    xyz_flag: [1.0, 1.0, 1.0]

control_modes:
  idle: false

  abs_pos_abs_att:
    x: { p: 0.6, i: 0.0, d: 0.0, v: 0.0, pid_max: 30.0, pid_min: -30.0 }
    y: { p: 0.6, i: 0.0, d: 0.0, v: 0.0, pid_max: 30.0, pid_min: -30.0 }
    z: { p: 0.55, i: 0.0, d: 0.0, v: 0.0, pid_max: 30.0, pid_min: -30.0 }
    roll: { p: 1.2, i: 0.0, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    pitch: { p: 1.2, i: 0.0, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    yaw: { p: 1.2, i: 0.0, d: 0.05, v: 0.0, pid_max: 20.0, pid_min: -20.0 }

  abs_pos_rate_att:
    x: { p: 0.6, i: 0.0, d: 0.0, v: 0.0, pid_max: 30.0, pid_min: -30.0 }
    y: { p: 0.6, i: 0.0, d: 0.0, v: 0.0, pid_max: 30.0, pid_min: -30.0 }
    z: { p: 0.55, i: 0.0, d: 0.0, v: 0.0, pid_max: 30.0, pid_min: -30.0 }
    p: { p: 0.3, i: 0.0, d: 0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    q: { p: 0.3, i: 0.0, d: 0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    r: { p: 0.6, i: 30, d: 0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }

  rate_pos_abs_att:
    u: { p: 4.0, i: 10, d: 0.0, v: 0.0, pid_max: 3.0, pid_min: 3.0 }
    v: { p: 4.0, i: 10, d: 0.0, v: 0.0, pid_max: 3.0, pid_min: 3.0 }
    w: { p: 4.0, i: 3.5, d: 0.03, v: 0.0, pid_max: 3.0, pid_min: 3.0 }
    roll: { p: 1.2, i: 0.0, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    pitch: { p: 1.2, i: 0.0, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    yaw: { p: 1.2, i: 0.0, d: 0.05, v: 0.0, pid_max: 20.0, pid_min: -20.0 }

  rate_pos_rate_att:
    u: { p: 4.0, i: 10, d: 0.0, v: 0.0, pid_max: 3.0, pid_min: -3.0 }
    v: { p: 4.0, i: 10, d: 0.0, v: 0.0, pid_max: 3.0, pid_min: -3.0 }
    w: { p: 4.0, i: 3.5, d: 0.03, v: 0.0, pid_max: 3.0, pid_min: -3.0 }
    p: { p: 0.3, i: 0.0, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    q: { p: 0.3, i: 0.0, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
    r: { p: 0.6, i: 30, d: 0.0, v: 0.0, pid_max: 20.0, pid_min: -20.0 }
