import math

from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    tf_position = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.0",
            "--y",
            "-0.0",
            "--z",
            "-0.0",
            "--roll",
            "-0.0",
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "map",
            "--child-frame-id",
            "marlin_v2/odom",
        ],
    )

    tf_base_link_to_base_link_ned = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.0",
            "--y",
            "-0.0",
            "--z",
            "-0.0",
            "--roll",
            str(math.pi),
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link",
            "--child-frame-id",
            "marlin_v2/base_link_ned",
        ],
    )

    tf_front_cam = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.0",
            "--y",
            "-0.33",
            "--z",
            "-0.16631",
            "--roll",
            str(math.pi / 2),
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link_ned",
            "--child-frame-id",
            "marlin_v2/front_camera",
        ],
    )

    # tf_down_cam = Node(
    #     package="tf2_ros",
    #     executable="static_transform_publisher",
    #     arguments=["0.16", "0.0725", "0.15", "1.571", "0", "1.571", "base_link", "bluerov2/camera_right"],
    # )

    tf_dvl = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.0",
            "--y",
            "0.0",
            "--z",
            "0.015797",
            "--roll",
            "0.0",
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link_ned",
            "--child-frame-id",
            "marlin_v2/dvl_link",
        ],
    )

    tf_imu = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.0",
            "--y",
            "-0.15",
            "--z",
            "-0.2",
            "--roll",
            "0.0",
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link_ned",
            "--child-frame-id",
            "marlin_v2/imu_link",
        ],
    )

    tf_dropper = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "-0.19074",
            "--y",
            "0.40252",
            "--z",
            "0.15565",
            "--roll",
            "-0.0",
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link_ned",
            "--child-frame-id",
            "marlin_v2/dropper_link",
        ],
    )

    tf_grabber_left = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.056319",
            "--y",
            "0.3506",
            "--z",
            "0.13631",
            "--roll",
            "-0.0",
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link_ned",
            "--child-frame-id",
            "marlin_v2/left_grabber_link",
        ],
    )

    tf_grabber_right = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x",
            "0.091319",
            "--y",
            "0.35087",
            "--z",
            "0.13636",
            "--roll",
            "-0.0",
            "--pitch",
            "0.0",
            "--yaw",
            "0.0",
            "--frame-id",
            "marlin_v2/base_link_ned",
            "--child-frame-id",
            "marlin_v2/right_grabber_link",
        ],
    )

    thruster_transforms = [
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "-0.29",
                "--y",
                "0.34",
                "--z",
                "-0.08",
                "--roll",
                "0.0",
                "--pitch",
                "0.0",
                "--yaw",
                str(7 * math.pi / 4),
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_0_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "-0.29",
                "--y",
                "-0.34",
                "--z",
                "-0.08",
                "--roll",
                "0.0",
                "--pitch",
                "0.0",
                "--yaw",
                str(math.pi / 4),
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_1_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "0.29",
                "--y",
                "0.34",
                "--z",
                "-0.08",
                "--roll",
                "0.0",
                "--pitch",
                "0.0",
                "--yaw",
                str(5 * math.pi / 4),
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_2_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "0.29",
                "--y",
                "-0.34",
                "--z",
                "-0.08",
                "--roll",
                "0.0",
                "--pitch",
                "0.0",
                "--yaw",
                str(3 * math.pi / 4),
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_3_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "0.23",
                "--y",
                "-0.22",
                "--z",
                "0.0",
                "--roll",
                "0.0",
                "--pitch",
                str(math.pi / 2),
                "--yaw",
                "0.0",
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_4_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "-0.23",
                "--y",
                "-0.22",
                "--z",
                "0.0",
                "--roll",
                "0.0",
                "--pitch",
                str(math.pi / 2),
                "--yaw",
                "0.0",
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_5_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "0.23",
                "--y",
                "0.22",
                "--z",
                "0.0",
                "--roll",
                "0.0",
                "--pitch",
                str(math.pi / 2),
                "--yaw",
                "0.0",
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_6_link",
            ],
        ),
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            arguments=[
                "--x",
                "-0.23",
                "--y",
                "0.22",
                "--z",
                "0.0",
                "--roll",
                "0.0",
                "--pitch",
                str(math.pi / 2),
                "--yaw",
                "0.0",
                "--frame-id",
                "marlin_v2/base_link_ned",
                "--child-frame-id",
                "marlin_v2/thruster_7_link",
            ],
        ),
    ]

    return LaunchDescription(
        [
            tf_position,
            tf_base_link_to_base_link_ned,
            tf_front_cam,
            tf_dvl,
            tf_imu,
            tf_dropper,
            tf_grabber_left,
            tf_grabber_right,
            # tf_down_cam,
            *thruster_transforms,
        ]
    )
