<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sub_sim</name>
  <version>0.0.0</version>
  <description>Files and scripts relating to simulator</description>
  <maintainer email="avbotzco@gmail.com">AVBotz</maintainer>
  <license>Proprietary</license>

  <depend>python3-jinja2</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
