<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sub_control</name>
  <version>0.0.0</version>
  <description>Publishes thruster commands (-1 to 1) in response to current state and desired state.</description>
  <maintainer email="avbotzco@gmail.com">AVBotz</maintainer>
  <license>Proprietary</license>

  <depend>angles</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>robot_localization</depend>
  <depend>std_msgs</depend>
  <depend>sub_control_interfaces</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
